# Site settings
title: Japan Container Days v18.12
email: info@thinkit.co.jp
baseurl: "https://containerdays.jp"
url: "https://containerdays.jp"
description: "[4/19開催]KubernetesやDockerを中心としたコンテナ活用の現状をひとまとめにした開発者のためのイベント"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#2f962b'

# Footer settings
footer: Impress Corporation, All rights reserved.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/containerdaysjp
  - title: facebook
    url: https://www.facebook.com/JapanContainerDays/
  - title: github
    url: https://github.com/containerdays

# Build settings
markdown: kramdown
permalink: pretty
